plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = "boc-${minecraft_version}-fabric"
}

sourceSets {
    main {
        java {
            srcDirs += ['../Common/src/main/java', '../Common/src/client/java']
        }
        resources {
            srcDirs += ['../Common/src/main/resources']
        }
    }
}

repositories {
    maven { url = 'https://maven.terraformersmc.com/releases' }
    maven {
        url "https://cursemaven.com"
    }
}

loom {
    mods {
        "blockoutlinecustomizer" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // ModMenu config screen integration (compile against the API only)
    compileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"

    runtimeOnly "curse.maven:sodium-394468:8261462"
    runtimeOnly "curse.maven:irisshaders-455508:8261499"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

jar {
    inputs.property "archivesName", project.base.archivesName
    from(rootProject.file("LICENSE")) {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}