# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=26.1.2
minecraft_version_range=[26.1,)

# Parchment
#parchment_minecraft_version=26.1.2
#parchment_mappings_version=2025.12.20

# NeoForge
neo_version=26.1.2.12-beta
neo_version_range=[26,27)
loader_version_range=[1,)

# Fabric
loader_version=0.18.6
loom_version=1.15-SNAPSHOT
maven_group=dev.anomz
fabric_api_version=0.146.0+26.1.2
archives_base_name=blockoutlinecustomizer

# Mod Properties
mod_id=blockoutlinecustomizer
mod_name=Block Outline Customizer
mod_license=All Rights Reserved
mod_version=1.3
mod_group_id=me.anomz.blockoutline
mod_authors=Anomz
mod_description=Customize your block selection outline with RGB colors, opacity, and variable thickness!